### ISSUE TITLE
Error loading deambooth extension

### ISSUE THREAD

**Issue by TentacleSama4254** [d8ahazard/sd_dreambooth_extension#1081]
### 0. Initial troubleshooting
Please check each of these before opening an issue. If you've checked them, **delete this section of your bug report**. Have you:
- Updated the Stable-Diffusion-WebUI to the latest version?
- Updated Dreambooth to the latest revision?
- Completely restarted the stable-diffusion-webUI, not just reloaded the UI?
- Read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?

### 1. Please find the following lines in the console and paste them below.

```
Startup time: 0.6s (load scripts: 0.1s, create ui: 0.3s).
Base dir (auto1111) is: /workspace/sd/stable-diffusion-webui from /workspace/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/install.py
Ext dir already in path? /workspace/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension
['/workspace/sd/stablediffusion/src/k-diffusion', '/usr/local/lib/python3.10/dist-packages/git/ext/gitdb', '/workspace/sd/stable-diffusion-webui', '/workspace/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension', '/workspace/sd/stable-diffusion-webui', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/workspace/sd/stablediffusion', '/workspace/sd/stablediffusion/src/taming-transformers', '/workspace/sd/stablediffusion/src/codeformer', '/workspace/sd/stablediffusion/src/blip', '/usr/local/lib/python3.10/dist-packages/gitdb/ext/smmap']

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.10 (main, Feb  8 2023, 14:50:01) [GCC 9.4.0]
Dreambooth revision: 8e7277b7ec30801753e3591e0e1139b97ec88e56
SD-WebUI revision: 

Checking Dreambooth requirements...
Failed to install Dreambooth requirements.
[+] torch version 1.13.1+cu116 installed.
[+] torchvision version 0.14.1+cu116 installed.
[+] xformers version 0.0.17.dev451 installed.
[!] accelerate version 0.12.0 installed.
[!] bitsandbytes version 0.35.0 installed.
[!] diffusers version 0.9.0.dev0 installed.
[!] transformers version 4.21.1 installed.
Launch errors detected: 
Incorrect version of accelerate installed.
Incorrect version of bitsandbytes installed.
Incorrect version of diffusers installed.
Incorrect version of transformers installed.

#######################################################################################################
```

### 2. Describe the bug

dreambooth extension does not appear on the UI

### 3. Provide logs
```
Script path is 
Exception importing api
Traceback (most recent call last):
  File "/workspace/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 27, in <module>
    from dreambooth.dataclasses.db_config import from_file, DreamboothConfig
  File "/workspace/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 10, in <module>
    from dreambooth.utils.image_utils import get_scheduler_names  # noqa
  File "/workspace/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ImportError: cannot import name 'KarrasDiffusionSchedulers' from 'diffusers.schedulers' (/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/__init__.py)
No, really, API loaded, wtf...
Error loading script: main.py
Traceback (most recent call last):
  File "/workspace/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/workspace/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 7, in <module>
    from dreambooth.dataclasses.db_config import (
  File "/workspace/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 10, in <module>
    from dreambooth.utils.image_utils import get_scheduler_names  # noqa
  File "/workspace/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ImportError: cannot import name 'KarrasDiffusionSchedulers' from 'diffusers.schedulers' (/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/__init__.py)

Loading weights [4c86efd062] from /workspace/sd/stable-diffusion-webui/models/Stable-diffusion/SDv1-5.ckpt
Creating model from config: /workspace/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 16.2s (load weights from disk: 0.8s, create model: 1.3s, apply weights to model: 5.7s, apply half(): 7.1s, load VAE: 1.0s, move model to device: 0.2s).
Running on local URL:
```
### 4. Environment

What OS? Linux?
Running on Runpod 
1 x RTX 3090
12 vCPU 58 GB RAM

**Comment by ArrowM** [comment]
As the log indicates, you libraries aren't updated. Do you have a startup flag set to disable library installs?

**Comment by TentacleSama4254** [comment]
> As the log indicates, your libraries aren't updated. Do you have a startup flag set to disable library installs?

not sure myself but I AM running satable diffusuin using this preset in Runpod

https://github.com/TheLastBen/fast-stable-diffusion

**Comment by ArrowM** [comment]
This is extension is designed for https://github.com/AUTOMATIC1111/stable-diffusion-webui (it may work with other projects though).
Please try running this then restart:
```
./venv/Scripts/activate
pip install -r ./extensions/sd_dreambooth_extension/requirements.txt
```

**Comment by TentacleSama4254** [comment]
> ./venv/Scripts/activate
> pip install -r ./extensions/sd_dreambooth_extension/requirements.txt

after running the file i got this errr

```
root@5ca0ae97cb45:/workspace/sd/stable-diffusion-webui# pip install -r ./extensions/sd_dreambooth_extension/requirements.txt
Ignoring mediapipe-silicon: markers 'sys_platform == "darwin"' don't match your environment
Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Collecting accelerate==0.17.1
  Using cached accelerate-0.17.1-py3-none-any.whl (212 kB)
Collecting albumentations~=1.3.0
  Using cached albumentations-1.3.0-py3-none-any.whl (123 kB)
Collecting bitsandbytes==0.35.4
  Using cached bitsandbytes-0.35.4-py3-none-any.whl (62.5 MB)
Collecting dadaptation==1.5.0
  Using cached dadaptation-1.5.tar.gz (8.3 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py", line 415, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 577, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/misc.py", line 701, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools'
```

**Comment by ArrowM** [comment]
That is not an error specific to this extension and a quick google search should tell you how to fix that (and similar issues). Could you please attempt to address that issue on your own and lmk if you get stuck or back to an extension-specific issue.

**Comment by Dancewithcrows** [comment]
I saw people getting this error on Reddit last night. Seems to be wider spread than I thought. I started to get it as well. It happened after I updated all my extensions.

**Comment by ArrowM** [comment]
> I saw people getting this error on Reddit last night. Seems to be wider spread than I thought. I started to get it as well. It happened after I updated all my extensions.

Are you talking about `ModuleNotFoundError: No module named 'setuptools'` or the original issue? Also please post a link to the reddit post(s) if you still have them.

Also, I'm updating the install process to be more resilient and easier to troubleshoot.

**Comment by Dancewithcrows** [comment]
https://www.reddit.com/r/DreamBooth/comments/11te2c9/failed_installation/jclaqvt/?context=3 

I'm referring to the dreambooth extension issue

**Comment by KaracaMert** [comment]
> https://www.reddit.com/r/DreamBooth/comments/11te2c9/failed_installation/jclaqvt/?context=3
> 
> I'm referring to the dreambooth extension issue

That was my post and I think I have found a workaround. I tried to update all the modules and for some reason I got an access error. So I made a clean install to a different directory and before installing dreambooth. I have updated all the necessary modules but still got the error, even though I knew that all the modules were installed with a correct version.

So I have done this:

(To force sd-web-ui to only install one set of requirements and resolve many issues on install, we can specify the command line argument:

set/export REQS_FILE=.\extensions\sd_dreambooth_extension\requirements.txt

Refer to the appropriate script below for extra flags to install requirements:

https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/webui-user-dreambooth.bat https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/webui-user-dreambooth.sh

And last, if you wish to completely skip the "native" install routine of Dreambooth, you can set the following environment flag: DREAMBOOTH_SKIP_INSTALL=True.)

After that I have also modified the requirements.txt to match the written versions and I still get errors on the start-up but I have the Dreambooth in the WebUI and it is functional.

**Comment by ArrowM** [comment]
Alrighty. All these issues should be fixed by #1082 which will hopefully be merged to main tomorrow.

**Comment by MaxPeckCreate** [comment]
![what](https://user-images.githubusercontent.com/126893828/226126057-f8421dd9-030e-4869-a3fd-edb4ff8d565d.jpg)
Not sure what the issue us - everything is installed and has a + mark but still fails

**Comment by TentacleSama4254** [comment]
> Alrighty. All these issues should be fixed by #1082 which will hopefully be merged to main tomorrow.

indeed this was fixed after the merge. Thank you!

![image](https://user-images.githubusercontent.com/74726248/226136812-38a11042-ab92-403d-b3f5-cd7fa66e54f1.png)

**Comment by ArrowM** [comment]
♥️
