### ISSUE TITLE
training worked once. Then wanted to train again. training failes at initializing dreambooth training

### ISSUE THREAD

**Issue by peterschwarz1** [d8ahazard/sd_dreambooth_extension#171]
**Have you read the Readme?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is 3b3a8002da3a780c276934e8bcf308aa822f1e22
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

Dreambooth revision is 5d8a331a142abe15516bec8f9a069241ed28c239
[!] Not using xformers memory efficient attention.
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Copying 8Bit Adam files for Windows.

**Describe the bug**

i was able to do the training once. As i noticed the results were not as i wanted them wanted to train again. Since then training "completes" after 0% steps.. see in log

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Scheduler Loaded
 Allocated: 0.3GB
 Reserved: 0.3GB

Steps:   0%|                                                                                                | 0/1700 [00:00<?, ?it/s] Exception while training: integer division or modulo by zero
 Allocated: 4.0GB
 Reserved: 4.1GB

Traceback (most recent call last):
  File "C:\Tools\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 935, in main
    for step, batch in enumerate(train_dataloader):
  File "C:\Tools\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 376, in __iter__
    current_batch = next(dataloader_iter)
  File "C:\Tools\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Tools\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Tools\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Tools\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Tools\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 445, in __getitem__
    instance_path, instance_prompt, instance_text = self.instance_images_path[index % self.num_instance_images]
ZeroDivisionError: integer division or modulo by zero
 Exception while training: integer division or modulo by zero
 Allocated: 4.0GB
 Reserved: 4.1GB

Traceback (most recent call last):
  File "C:\Tools\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 935, in main
    for step, batch in enumerate(train_dataloader):
  File "C:\Tools\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 376, in __iter__
    current_batch = next(dataloader_iter)
  File "C:\Tools\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Tools\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Tools\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Tools\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Tools\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 445, in __getitem__
    instance_path, instance_prompt, instance_text = self.instance_images_path[index % self.num_instance_images]
ZeroDivisionError: integer division or modulo by zero
 CLEANUP:
 Allocated: 4.0GB
 Reserved: 4.1GB

 Cleanup Complete.
 Allocated: 3.7GB
 Reserved: 4.0GB

Steps:   0%|                                                                                                | 0/1700 [00:00<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Memory output: {'VRAM cleared.': '0.0/0.0GB', 'Training completed, reloading SD Model.': '0.0/0.0GB'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 0

**Environment**
What OS? Windows 11
If Windows - WSL or native?
What GPU are you using? RTX 3090 24gb

**Comment by peterschwarz1** [comment]
ZeroDivisionError: integer division or modulo by zero

anyone knows how to fix?

**Comment by d8ahazard** [comment]
This error is saying you have no images in your instance_data dir.

I've pushed some additional code to handle this or at least yell at you without breaking.

Give it a go and let me know what happens.

f946126

**Comment by peterschwarz1** [comment]
damn still getting the same error. the instance_data dir is my "Dataset directory" right?
I've images on that path. It was on another drive. Now relocated to the same drive but still the same error.

**Comment by peterschwarz1** [comment]
It seems to work now. Thank you so much!!

**Comment by wukao1985** [comment]
> It seems to work now. Thank you so much!!

How did you solve it? I have the same issue
