### ISSUE TITLE
Error when generating a preview image

### ISSUE THREAD

**Issue by Trauter1** [d8ahazard/sd_dreambooth_extension#23]
```
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/notebooks/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 256, in start_training
    trained_steps = main(config)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 829, in main
    g_cuda = torch.Generator(device=accelerator.device).manual_seed(args.seed)
AttributeError: 'DreamboothConfig' object has no attribute 'seed'
```

Worked fine before updating to the latest version.

**Comment by gonjay** [comment]
Change this line
```
parser.add_argument("--seed", type=int, default=None, help="A seed for reproducible training.")
```

to:

```
parser.add_argument("--seed", type=int, default=2333, help="A seed for reproducible training.")
```

Then reload webui

**Comment by Trauter1** [comment]
Sadly, it doesn't work for me. Im running paperspace notebook it that matters. @gonjay

**Comment by rabidcopy** [comment]
Same.
```
Traceback (most recent call last):
  File "/notebooks/SDW/modules/ui.py", line 180, in f
    res = list(func(*args, **kwargs))
  File "/notebooks/SDW/webui.py", line 55, in f
    res = func(*args, **kwargs)
  File "/notebooks/SDW/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 256, in start_training
    trained_steps = main(config)
  File "/notebooks/SDW/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 829, in main
    g_cuda = torch.Generator(device=accelerator.device).manual_seed(args.seed)
AttributeError: 'DreamboothConfig' object has no attribute 'seed'
```

**Comment by Dawgmastah** [comment]
Can confirm the issue, last night preview images worked fine

**Comment by entmike** [comment]
Same issue I just reported here (didn't notice you already had one open here based on subject line) https://github.com/d8ahazard/sd_dreambooth_extension/issues/30

**Comment by rabidcopy** [comment]
Possibly fixed by https://github.com/d8ahazard/sd_dreambooth_extension/commit/fc5f05410fc57e706f8adab9e8564567186a768a. Can't test right now.

**Comment by d8ahazard** [comment]
Think I got it now:

9e6ebef

**Comment by Wakzor** [comment]
Im still having an error when generating preview.  CPU: False Adam: True, Prec: bf16, Prior: False, Grad: True, TextTr: True
`  File "C:\Users\user\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\user\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\Users\user\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "C:\Users\user\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 829, in main
    revision=args.revision,
AttributeError: 'DreamboothConfig' object has no attribute 'revision'`

**Comment by MalOMaw** [comment]
Still broken as of right now

**Comment by d8ahazard** [comment]
This issue has been resolved.
