### ISSUE TITLE
AttributeError: 'DreamboothConfig' object has no attribute 'seed'

### ISSUE THREAD

**Issue by entmike** [d8ahazard/sd_dreambooth_extension#30]
Hello!  When trying to train from A1111 extension (great job, BTW!!!!), I receive the following error after the first checkpoint at 500 is saved:

```
Traceback (most recent call last):
  File "/home/stable/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/home/stable/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/home/stable/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 256, in start_training
    trained_steps = main(config)
  File "/home/stable/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 833, in main
    g_cuda = torch.Generator(device=accelerator.device).manual_seed(args.seed)
AttributeError: 'DreamboothConfig' object has no attribute 'seed'
```

**Comment by d8ahazard** [comment]
Fixed with 43ec3b6

**Comment by entmike** [comment]
See my comments here, it is still broken:

https://github.com/d8ahazard/sd_dreambooth_extension/commit/43ec3b6a0dfe2b0ea6b9cebf9815a06e3375d5c2
