### ISSUE TITLE
Error running install.py for extension sd_dreambooth_extension

### ISSUE THREAD

**Issue by TechnoClasher** [d8ahazard/sd_dreambooth_extension#88]
**Have you read the Readme?**

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

**Have you updated Dreambooth to the latest revision?**

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

Installing requirements for Web UI
Error running install.py for extension sd_dreambooth_extension.
Command: "E:\ai\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: Requirement already satisfied: basicsr in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 1)) (1.4.2)
Requirement already satisfied: diffusers in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 2)) (0.3.0)
Collecting fairscale==0.4.4
  Using cached fairscale-0.4.4.tar.gz (235 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: fonts in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 4)) (0.0.3)
Requirement already satisfied: font-roboto in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 5)) (0.0.1)
Requirement already satisfied: gfpgan in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 6)) (1.3.8)
Requirement already satisfied: gradio==3.9 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 7)) (3.9)
Collecting invisible-watermark
  Using cached invisible_watermark-0.1.5-py3-none-any.whl (1.6 MB)
Requirement already satisfied: numpy in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 9)) (1.23.3)
Requirement already satisfied: omegaconf in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 10)) (2.2.3)
Requirement already satisfied: opencv-python in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 11)) (4.6.0.66)
Requirement already satisfied: requests in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 12)) (2.25.1)
Requirement already satisfied: piexif in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 13)) (1.1.3)
Requirement already satisfied: Pillow in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 14)) (9.2.0)
Collecting pytorch_lightning==1.7.7
  Using cached pytorch_lightning-1.7.7-py3-none-any.whl (708 kB)
Requirement already satisfied: realesrgan in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 16)) (0.3.0)
Requirement already satisfied: scikit-image>=0.19 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 17)) (0.19.2)
Collecting timm==0.4.12
  Downloading timm-0.4.12-py3-none-any.whl (376 kB)
     -------------------------------------- 377.0/377.0 kB 1.5 MB/s eta 0:00:00
Requirement already satisfied: transformers==4.19.2 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 19)) (4.19.2)
Requirement already satisfied: torch in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 20)) (1.12.1+cu116)
Requirement already satisfied: einops in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 21)) (0.4.1)
Requirement already satisfied: jsonmerge in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 22)) (1.8.0)
Requirement already satisfied: clean-fid in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 23)) (0.1.29)
Requirement already satisfied: resize-right in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 24)) (0.0.2)
Requirement already satisfied: torchdiffeq in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 25)) (0.2.3)
Requirement already satisfied: kornia in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 26)) (0.6.7)
Requirement already satisfied: lark in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 27)) (1.1.2)
Requirement already satisfied: inflection in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 28)) (0.5.1)
Requirement already satisfied: GitPython in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements.txt (line 29)) (3.1.27)
Requirement already satisfied: websockets in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (10.4)
Requirement already satisfied: h11<0.13,>=0.11 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (0.12.0)
Requirement already satisfied: fsspec in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (2022.10.0)
Requirement already satisfied: uvicorn in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (0.19.0)
Requirement already satisfied: markdown-it-py[linkify,plugins] in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (2.1.0)
Requirement already satisfied: aiohttp in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (3.8.3)
Requirement already satisfied: ffmpy in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (0.3.0)
Requirement already satisfied: matplotlib in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (3.6.2)
Requirement already satisfied: paramiko in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (2.12.0)
Requirement already satisfied: pandas in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (1.5.1)
Requirement already satisfied: pydub in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (0.25.1)
Requirement already satisfied: pycryptodome in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (3.15.0)
Requirement already satisfied: pyyaml in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (6.0)
Requirement already satisfied: fastapi in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (0.86.0)
Requirement already satisfied: python-multipart in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (0.0.4)
Requirement already satisfied: pydantic in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (1.10.2)
Requirement already satisfied: orjson in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (3.8.1)
Requirement already satisfied: jinja2 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (3.1.2)
Requirement already satisfied: httpx in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.9->-r requirements.txt (line 7)) (0.23.0)
Requirement already satisfied: packaging>=17.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (21.3)
Requirement already satisfied: typing-extensions>=4.0.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (4.4.0)
Requirement already satisfied: tensorboard>=2.9.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (2.11.0)
Requirement already satisfied: tqdm>=4.57.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (4.64.1)
Requirement already satisfied: torchmetrics>=0.7.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.10.2)
Requirement already satisfied: pyDeprecate>=0.3.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.3.2)
Requirement already satisfied: torchvision in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from timm==0.4.12->-r requirements.txt (line 18)) (0.13.1+cu116)
Requirement already satisfied: regex!=2019.12.17 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.19.2->-r requirements.txt (line 19)) (2022.10.31)
Requirement already satisfied: filelock in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.19.2->-r requirements.txt (line 19)) (3.8.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.19.2->-r requirements.txt (line 19)) (0.10.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.13,>=0.11.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.19.2->-r requirements.txt (line 19)) (0.12.1)
Requirement already satisfied: addict in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from basicsr->-r requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: future in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from basicsr->-r requirements.txt (line 1)) (0.18.2)
Requirement already satisfied: lmdb in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from basicsr->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: scipy in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from basicsr->-r requirements.txt (line 1)) (1.9.3)
Requirement already satisfied: tb-nightly in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from basicsr->-r requirements.txt (line 1)) (2.11.0a20221109)
Requirement already satisfied: yapf in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from basicsr->-r requirements.txt (line 1)) (0.32.0)
Requirement already satisfied: importlib-metadata in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from diffusers->-r requirements.txt (line 2)) (5.0.0)
Requirement already satisfied: facexlib>=0.2.5 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gfpgan->-r requirements.txt (line 6)) (0.2.5)
Requirement already satisfied: PyWavelets>=1.1.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from invisible-watermark->-r requirements.txt (line 8)) (1.4.1)
Collecting onnxruntime
  Downloading onnxruntime-1.13.1-cp310-cp310-win_amd64.whl (5.9 MB)
     ---------------------------------------- 5.9/5.9 MB 7.2 MB/s eta 0:00:00
Collecting onnx
  Downloading onnx-1.12.0-cp310-cp310-win_amd64.whl (11.5 MB)
     ---------------------------------------- 11.5/11.5 MB 7.4 MB/s eta 0:00:00
Requirement already satisfied: antlr4-python3-runtime==4.9.* in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from omegaconf->-r requirements.txt (line 10)) (4.9.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from requests->-r requirements.txt (line 12)) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from requests->-r requirements.txt (line 12)) (2022.9.24)
Requirement already satisfied: idna<3,>=2.5 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from requests->-r requirements.txt (line 12)) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from requests->-r requirements.txt (line 12)) (4.0.0)
Requirement already satisfied: tifffile>=2019.7.26 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.19->-r requirements.txt (line 17)) (2022.10.10)
Requirement already satisfied: networkx>=2.2 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.19->-r requirements.txt (line 17)) (2.8.8)
Requirement already satisfied: imageio>=2.4.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.19->-r requirements.txt (line 17)) (2.22.4)
Requirement already satisfied: jsonschema in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from jsonmerge->-r requirements.txt (line 22)) (4.17.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from GitPython->-r requirements.txt (line 29)) (4.0.9)
Requirement already satisfied: filterpy in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from facexlib>=0.2.5->gfpgan->-r requirements.txt (line 6)) (1.4.5)
Requirement already satisfied: numba in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from facexlib>=0.2.5->gfpgan->-r requirements.txt (line 6)) (0.56.4)
Requirement already satisfied: attrs>=17.3.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from aiohttp->gradio==3.9->-r requirements.txt (line 7)) (22.1.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from aiohttp->gradio==3.9->-r requirements.txt (line 7)) (4.0.2)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from aiohttp->gradio==3.9->-r requirements.txt (line 7)) (2.1.1)
Requirement already satisfied: aiosignal>=1.1.2 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from aiohttp->gradio==3.9->-r requirements.txt (line 7)) (1.3.1)
Requirement already satisfied: frozenlist>=1.1.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from aiohttp->gradio==3.9->-r requirements.txt (line 7)) (1.3.3)
Requirement already satisfied: yarl<2.0,>=1.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from aiohttp->gradio==3.9->-r requirements.txt (line 7)) (1.8.1)
Requirement already satisfied: multidict<7.0,>=4.5 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from aiohttp->gradio==3.9->-r requirements.txt (line 7)) (6.0.2)
Requirement already satisfied: smmap<6,>=3.0.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from gitdb<5,>=4.0.1->GitPython->-r requirements.txt (line 29)) (5.0.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from packaging>=17.0->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (3.0.9)
Requirement already satisfied: grpcio>=1.24.3 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (1.50.0)
Requirement already satisfied: werkzeug>=1.0.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (2.2.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.4.6)
Requirement already satisfied: markdown>=2.6.8 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (3.4.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (1.8.1)
Requirement already satisfied: absl-py>=0.4 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (1.3.0)
Requirement already satisfied: setuptools>=41.0.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (63.2.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.6.1)
Requirement already satisfied: wheel>=0.26 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.38.4)
Requirement already satisfied: protobuf<4,>=3.9.2 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (3.20.3)
Requirement already satisfied: google-auth<3,>=1.6.3 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (2.14.1)
Requirement already satisfied: colorama in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from tqdm>=4.57.0->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.4.6)
Requirement already satisfied: starlette==0.20.4 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from fastapi->gradio==3.9->-r requirements.txt (line 7)) (0.20.4)
Requirement already satisfied: anyio<5,>=3.4.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from starlette==0.20.4->fastapi->gradio==3.9->-r requirements.txt (line 7)) (3.6.2)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from httpx->gradio==3.9->-r requirements.txt (line 7)) (1.5.0)
Requirement already satisfied: httpcore<0.16.0,>=0.15.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from httpx->gradio==3.9->-r requirements.txt (line 7)) (0.15.0)
Requirement already satisfied: sniffio in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from httpx->gradio==3.9->-r requirements.txt (line 7)) (1.3.0)
Requirement already satisfied: zipp>=0.5 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from importlib-metadata->diffusers->-r requirements.txt (line 2)) (3.10.0)
Requirement already satisfied: MarkupSafe>=2.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from jinja2->gradio==3.9->-r requirements.txt (line 7)) (2.1.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from jsonschema->jsonmerge->-r requirements.txt (line 22)) (0.19.2)
Requirement already satisfied: mdurl~=0.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from markdown-it-py[linkify,plugins]->gradio==3.9->-r requirements.txt (line 7)) (0.1.2)
Requirement already satisfied: linkify-it-py~=1.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from markdown-it-py[linkify,plugins]->gradio==3.9->-r requirements.txt (line 7)) (1.0.3)
Requirement already satisfied: mdit-py-plugins in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from markdown-it-py[linkify,plugins]->gradio==3.9->-r requirements.txt (line 7)) (0.3.1)
Requirement already satisfied: fonttools>=4.22.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->gradio==3.9->-r requirements.txt (line 7)) (4.38.0)
Requirement already satisfied: kiwisolver>=1.0.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->gradio==3.9->-r requirements.txt (line 7)) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->gradio==3.9->-r requirements.txt (line 7)) (2.8.2)
Requirement already satisfied: cycler>=0.10 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->gradio==3.9->-r requirements.txt (line 7)) (0.11.0)
Requirement already satisfied: contourpy>=1.0.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->gradio==3.9->-r requirements.txt (line 7)) (1.0.6)
Collecting protobuf<4,>=3.9.2
  Using cached protobuf-3.20.1-cp310-cp310-win_amd64.whl (903 kB)
Collecting flatbuffers
  Using cached flatbuffers-22.10.26-py2.py3-none-any.whl (26 kB)
Collecting coloredlogs
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting sympy
  Using cached sympy-1.11.1-py3-none-any.whl (6.5 MB)
Requirement already satisfied: pytz>=2020.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from pandas->gradio==3.9->-r requirements.txt (line 7)) (2022.6)
Requirement already satisfied: pynacl>=1.0.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from paramiko->gradio==3.9->-r requirements.txt (line 7)) (1.5.0)
Requirement already satisfied: bcrypt>=3.1.3 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from paramiko->gradio==3.9->-r requirements.txt (line 7)) (4.0.1)
Requirement already satisfied: six in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from paramiko->gradio==3.9->-r requirements.txt (line 7)) (1.16.0)
Requirement already satisfied: cryptography>=2.5 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from paramiko->gradio==3.9->-r requirements.txt (line 7)) (38.0.3)
Requirement already satisfied: click>=7.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from uvicorn->gradio==3.9->-r requirements.txt (line 7)) (8.1.3)
Requirement already satisfied: cffi>=1.12 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from cryptography>=2.5->paramiko->gradio==3.9->-r requirements.txt (line 7)) (1.15.1)
Requirement already satisfied: rsa<5,>=3.1.4 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (5.2.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (1.3.1)
Requirement already satisfied: uc-micro-py in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from linkify-it-py~=1.0->markdown-it-py[linkify,plugins]->gradio==3.9->-r requirements.txt (line 7)) (1.0.1)
Collecting humanfriendly>=9.1
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from numba->facexlib>=0.2.5->gfpgan->-r requirements.txt (line 6)) (0.39.1)
Collecting mpmath>=0.19
  Using cached mpmath-1.2.1-py3-none-any.whl (532 kB)
Requirement already satisfied: pycparser in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from cffi>=1.12->cryptography>=2.5->paramiko->gradio==3.9->-r requirements.txt (line 7)) (2.21)
Collecting pyreadline3
  Using cached pyreadline3-3.4.1-py3-none-any.whl (95 kB)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in e:\ai\stable-diffusion-webui\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.9.1->pytorch_lightning==1.7.7->-r requirements.txt (line 15)) (3.2.2)
Building wheels for collected packages: fairscale
  Building wheel for fairscale (pyproject.toml): started
  Building wheel for fairscale (pyproject.toml): finished with status 'done'
  Created wheel for fairscale: filename=fairscale-0.4.4-py3-none-any.whl size=292848 sha256=904495975f086a334998532e4ae35ff5554cd11c70aeda2b221aa6d82909e12a
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\eb\a6\30\67ce96af10c2038bd71b851f60f388fc7922cc663ed954262d
Successfully built fairscale
Installing collected packages: pyreadline3, mpmath, flatbuffers, sympy, protobuf, humanfriendly, onnx, fairscale, coloredlogs, timm, onnxruntime, invisible-watermark, pytorch_lightning
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
  Attempting uninstall: fairscale
    Found existing installation: fairscale 0.4.9
    Uninstalling fairscale-0.4.9:
      Successfully uninstalled fairscale-0.4.9
  Attempting uninstall: timm
    Found existing installation: timm 0.6.7
    Uninstalling timm-0.6.7:
      Successfully uninstalled timm-0.6.7
  Attempting uninstall: pytorch_lightning
    Found existing installation: pytorch-lightning 1.7.6
    Uninstalling pytorch-lightning-1.7.6:
      Successfully uninstalled pytorch-lightning-1.7.6
Successfully installed coloredlogs-15.0.1 fairscale-0.4.4 flatbuffers-22.10.26 humanfriendly-10.0 invisible-watermark-0.1.5 mpmath-1.2.1 onnx-1.12.0 onnxruntime-1.13.1 protobuf-3.20.1 pyreadline3-3.4.1 pytorch_lightning-1.7.7 sympy-1.11.1 timm-0.4.12

stderr: E:\ai\stable-diffusion-webui\venv\Scripts\python.exe: Error while finding module specification for 'pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 ' (ModuleNotFoundError: No module named 'pip install torch==1')
Traceback (most recent call last):
  File "E:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 14, in <module>
    subprocess.check_call([sys.executable, '-m', torch_cmd])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['E:\\ai\\stable-diffusion-webui\\venv\\Scripts\\python.exe', '-m', 'pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 ']' returned non-zero exit status 1.

Launching Web UI with arguments: --autolaunch
Error loading script: main.py
Traceback (most recent call last):
  File "E:\ai\stable-diffusion-webui\modules\scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "E:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "E:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 26, in <module>
    from dreambooth.dreambooth import get_db_models
  File "E:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 10, in <module>
    from dreambooth.train_dreambooth import main
  File "E:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 20, in <module>
    from accelerate import Accelerator
ModuleNotFoundError: No module named 'accelerate'

`Dreambooth revision is 3b3a8002da3a780c276934e8bcf308aa822f1e22
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

**Describe the bug**
Dreambooth tab doesnt show up in the stable diffusion after its installed. At first it even broke my stable diffusion and had to copy the files from the github again, After now stable diffusion is fixed, dreambooth still doesnt show up in stable diffusion

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**
What OS?
Windows
If Windows - WSL or native?
WSL
What GPU are you using?
RTX 3070 Ti

**Comment by arifszn** [comment]
Having the same issue on RTX 3060.

**Comment by xiaolxl** [comment]
尝试运行pip install accelerate安装它

Try running pip install accelerate to install it

**Comment by arifszn** [comment]
> 尝试运行pip install accelerate安装它
> 
> Try running pip install accelerate to install it

Still the same after running it.

**Comment by xiaolxl** [comment]
安装后如果还是报错(ModuleNotFoundError: No module named 'pip install torch==1')是正常的，可以直接打开webui尝试训练，今天带着这个错误，也成功训练了一次

After installation, if the error (ModuleNotFoundError: No module named 'pip install torch==1') is normal, you can directly open the webui to try training. Today, with this error, you also successfully trained once

**Comment by arifszn** [comment]
> 安装后如果还是报错(ModuleNotFoundError: No module named 'pip install torch==1')是正常的，可以直接打开webui尝试训练，今天带着这个错误，也成功训练了一次
> 
> After installation, if the error (ModuleNotFoundError: No module named 'pip install torch==1') is normal, you can directly open the webui to try training. Today, with this error, you also successfully trained once

No tab for the dreambooth.

![image](https://user-images.githubusercontent.com/45073703/201060117-4b45133f-12f7-47a2-98e5-4ea1c6bf776a.png)

**Comment by YakuzaSuske** [comment]
Guys i recommend downloading this version. its older but it works for me, hopefully it works for some of ya'll
https://github.com/d8ahazard/sd_dreambooth_extension/tree/6f81b3b5be180123efabf1f2780aacf5ba16c95c

**Comment by xiaolxl** [comment]
> > 安装后如果还是报错(ModuleNotFoundError: No module named 'pip install torch==1')是正常的，可以直接打开webui尝试训练，今天带着这个错误，也成功训练了一次
> > After installation, if the error (ModuleNotFoundError: No module named 'pip install torch==1') is normal, you can directly open the webui to try training. Today, with this error, you also successfully trained once
> 
> No tab for the dreambooth.
> 
> ![image](https://user-images.githubusercontent.com/45073703/201060117-4b45133f-12f7-47a2-98e5-4ea1c6bf776a.png)

你是在扩展管理上直接安装的吗？
我是用的命令手动git clone的

Do you install it directly on extension management?
I used the command to manually git clone

**Comment by AntiCensor** [comment]
I have this same issue, I only managed to get it to partially work by taking the site-packages from my system's python in AppData\Local\Programs\Python\Python310\Lib\site-packages and moving the two folders, accelerate and accelerate-0.13.2.dist info. to stable-diffusion-webui\venv\Lib\site-packages...

It gets the dreambooth icon to appear... But I still have other issues that I have yet to solve.

**Comment by xiaolxl** [comment]
> I have this same issue, I only managed to get it to partially work by taking the site-packages from my system's python in AppData\Local\Programs\Python\Python310\Lib\site-packages and moving the two folders, accelerate and accelerate-0.13.2.dist info. to stable-diffusion-webui\venv\Lib\site-packages...
> 
> It gets the dreambooth icon to appear... But I still have other issues that I have yet to solve.
> 
> Upon initiation of training after my fix, i get this : AttributeError: 'UNet2DConditionModel' object has no attribute 'enable_gradient_checkpointing' occurs.

![0A~4TU0%74PSYD%BHM)8Z6Y](https://user-images.githubusercontent.com/56190732/201067731-a4225301-0371-4613-b96b-f2bfd31ce6b3.png)

找到dreambooth下的dreambooth文件夹，修改train_dreambooth.py文件中的第615行将它注释掉

Find the dreambooth folder under dreambooth and modify the train_ Comment it out on line 615 in the dreambooth. py file

**Comment by xiaolxl** [comment]
> > I have this same issue, I only managed to get it to partially work by taking the site-packages from my system's python in AppData\Local\Programs\Python\Python310\Lib\site-packages and moving the two folders, accelerate and accelerate-0.13.2.dist info. to stable-diffusion-webui\venv\Lib\site-packages...
> > It gets the dreambooth icon to appear... But I still have other issues that I have yet to solve.
> > Upon initiation of training after my fix, i get this : AttributeError: 'UNet2DConditionModel' object has no attribute 'enable_gradient_checkpointing' occurs.
> 
> ![0A~4TU0%74PSYD%BHM)8Z6Y](https://user-images.githubusercontent.com/56190732/201067731-a4225301-0371-4613-b96b-f2bfd31ce6b3.png)
> 
> 找到dreambooth下的dreambooth文件夹，修改train_dreambooth.py文件中的第615行将它注释掉
> 
> Find the dreambooth folder under dreambooth and modify the train_ Comment it out on line 615 in the dreambooth. py file

这样做可以保证在第一个检查点输出ckpt，但第二个会失败，所以保存步数请设置到合适值，最大步数请设置得比保存步数大

This ensures that ckpt will be output at the first checkpoint, but the second checkpoint will fail, so please set the number of saving steps to an appropriate value, and the maximum number of steps should be larger than the number of saving steps

**Comment by dikasterion** [comment]
> 



> I have the same issue... the same error message and no tab for dreambooth

oh it's now working...

**Comment by gmaciocci** [comment]
> Guys i recommend downloading this version. its older but it works for me, hopefully it works for some of ya'll https://github.com/d8ahazard/sd_dreambooth_extension/tree/6f81b3b5be180123efabf1f2780aacf5ba16c95c

Yep, that worked, thank you. Must be something very wrong with the current commit.

**Comment by d8ahazard** [comment]
This should be fixed with the latest commit(s).

**Comment by 0xBYTESHIFT** [comment]
still happens with latest master. no tab. log from google colab:

stdout: Installing requirements for Dreambooth
Checking Dreambooth requirements.

stderr: Traceback (most recent call last):
  File "/content/stable-diffusion-webui/extensions/db/install.py", line 18, in <module>
    f"Couldn't install {name} requirements.")
  File "/content/stable-diffusion-webui/launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install Dreambooth requirements..
Command: "/usr/bin/python3" -m pip install -r "/content/stable-diffusion-webui/extensions/db/requirements.txt"
Error code: 1
stdout: Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting GitPython==3.1.27
  Using cached GitPython-3.1.27-py3-none-any.whl (181 kB)
Collecting Pillow==9.2.0
  Using cached Pillow-9.2.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Requirement already satisfied: accelerate==0.14.0 in /usr/local/lib/python3.7/dist-packages (from -r /content/stable-diffusion-webui/extensions/db/requirements.txt (line 3)) (0.14.0)
Collecting albumentations==1.3.0
  Using cached albumentations-1.3.0-py3-none-any.whl (123 kB)
Requirement already satisfied: basicsr==1.4.2 in /usr/local/lib/python3.7/dist-packages (from -r /content/stable-diffusion-webui/extensions/db/requirements.txt (line 5)) (1.4.2)
Collecting bitsandbytes==0.35.0
  Using cached bitsandbytes-0.35.0-py3-none-any.whl (62.5 MB)
Collecting clean-fid==0.1.29
  Using cached clean_fid-0.1.29-py3-none-any.whl (24 kB)
Requirement already satisfied: diffusers==0.7.2 in /usr/local/lib/python3.7/dist-packages (from -r /content/stable-diffusion-webui/extensions/db/requirements.txt (line 8)) (0.7.2)
Collecting einops==0.4.1
  Using cached einops-0.4.1-py3-none-any.whl (28 kB)

stderr: ERROR: Could not find a version that satisfies the requirement fairscale==0.4.9 (from versions: 0.0.0, 0.0.1, 0.0.2, 0.0.3, 0.1.0, 0.1.1, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6)
ERROR: No matching distribution found for fairscale==0.4.9

**Comment by AoSankaku** [comment]
Exactly the same issue on Google Colab, and https://github.com/d8ahazard/sd_dreambooth_extension/tree/6f81b3b5be180123efabf1f2780aacf5ba16c95c couldn't be cloned.
"!git clone -b https://github.com/d8ahazard/sd_dreambooth_extension/tree/6f81b3b5be180123efabf1f2780aacf5ba16c95c" returns nothing but "not found" error.

Cloning on Extensions tab won't work properly. No new tab is shown though there's "sd_dreambooth_extension" in Extensions/Installed tab.


Error running install.py for extension extensions/sd_dreambooth_extension.
Command: "/usr/bin/python3" "extensions/sd_dreambooth_extension/install.py"
Error code: 1
stdout: Installing requirements for Dreambooth
Checking Dreambooth requirements.

stderr: Traceback (most recent call last):
  File "extensions/sd_dreambooth_extension/install.py", line 18, in <module>
    f"Couldn't install {name} requirements.")
  File "/content/stable-diffusion-webui/launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install Dreambooth requirements..
Command: "/usr/bin/python3" -m pip install -r "/content/stable-diffusion-webui/extensions/sd_dreambooth_extension/requirements.txt"
Error code: 1
stdout: Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting GitPython==3.1.27
  Downloading GitPython-3.1.27-py3-none-any.whl (181 kB)
Collecting Pillow==9.2.0
  Downloading Pillow-9.2.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Requirement already satisfied: accelerate==0.14.0 in /usr/local/lib/python3.7/dist-packages (from -r /content/stable-diffusion-webui/extensions/sd_dreambooth_extension/requirements.txt (line 3)) (0.14.0)
Collecting albumentations==1.3.0
  Downloading albumentations-1.3.0-py3-none-any.whl (123 kB)
Requirement already satisfied: basicsr==1.4.2 in /usr/local/lib/python3.7/dist-packages (from -r /content/stable-diffusion-webui/extensions/sd_dreambooth_extension/requirements.txt (line 5)) (1.4.2)
Collecting bitsandbytes==0.35.0
  Downloading bitsandbytes-0.35.0-py3-none-any.whl (62.5 MB)
Collecting clean-fid==0.1.29
  Downloading clean_fid-0.1.29-py3-none-any.whl (24 kB)
Requirement already satisfied: diffusers==0.7.2 in /usr/local/lib/python3.7/dist-packages (from -r /content/stable-diffusion-webui/extensions/sd_dreambooth_extension/requirements.txt (line 8)) (0.7.2)
Collecting einops==0.4.1
  Downloading einops-0.4.1-py3-none-any.whl (28 kB)

stderr: ERROR: Could not find a version that satisfies the requirement fairscale==0.4.9 (from versions: 0.0.0, 0.0.1, 0.0.2, 0.0.3, 0.1.0, 0.1.1, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6)
ERROR: No matching distribution found for fairscale==0.4.9

stdout: Installing requirements for Dreambooth
Checking Dreambooth requirements.

**Comment by Aslopez369** [comment]
> still happens with latest master. no tab. log from google colab:
> 
> stdout: Installing requirements for Dreambooth Checking Dreambooth requirements.
> 
> stderr: Traceback (most recent call last): File "/content/stable-diffusion-webui/extensions/db/install.py", line 18, in f"Couldn't install {name} requirements.") File "/content/stable-diffusion-webui/launch.py", line 34, in run raise RuntimeError(message) RuntimeError: Couldn't install Dreambooth requirements.. Command: "/usr/bin/python3" -m pip install -r "/content/stable-diffusion-webui/extensions/db/requirements.txt" Error code: 1 stdout: Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/ Collecting GitPython==3.1.27 Using cached GitPython-3.1.27-py3-none-any.whl (181 kB) Collecting Pillow==9.2.0 Using cached Pillow-9.2.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB) Requirement already satisfied: accelerate==0.14.0 in /usr/local/lib/python3.7/dist-packages (from -r /content/stable-diffusion-webui/extensions/db/requirements.txt (line 3)) (0.14.0) Collecting albumentations==1.3.0 Using cached albumentations-1.3.0-py3-none-any.whl (123 kB) Requirement already satisfied: basicsr==1.4.2 in /usr/local/lib/python3.7/dist-packages (from -r /content/stable-diffusion-webui/extensions/db/requirements.txt (line 5)) (1.4.2) Collecting bitsandbytes==0.35.0 Using cached bitsandbytes-0.35.0-py3-none-any.whl (62.5 MB) Collecting clean-fid==0.1.29 Using cached clean_fid-0.1.29-py3-none-any.whl (24 kB) Requirement already satisfied: diffusers==0.7.2 in /usr/local/lib/python3.7/dist-packages (from -r /content/stable-diffusion-webui/extensions/db/requirements.txt (line 8)) (0.7.2) Collecting einops==0.4.1 Using cached einops-0.4.1-py3-none-any.whl (28 kB)
> 
> stderr: ERROR: Could not find a version that satisfies the requirement fairscale==0.4.9 (from versions: 0.0.0, 0.0.1, 0.0.2, 0.0.3, 0.1.0, 0.1.1, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6) ERROR: No matching distribution found for fairscale==0.4.9

Same problem if using the latest version of extension. I tried Google Colab with the previous version [6f81b3b5be180123efabf1f2780aacf5ba16c95c] mentioned by [YakuzaSuske](https://github.com/YakuzaSuske). The fairscale version problem is solved. But everytime I create a new model before training, the command line will be terminated before it is done.

**Comment by scythe000** [comment]
Still happening

**Comment by 100xDAO** [comment]
Error running install.py for extension D:\AI\SD\novelaiv3\extensions\sd_dreambooth_extension.
Command: "D:\AI\SD\novelaiv3\py310\python.exe" "D:\AI\SD\novelaiv3\extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth

Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641

# Requirement installation exception:

Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple, https://pypi.tuna.tsinghua.edu.cn/simple, https://mirrors.pku.edu.cn/pypi/simple, https://mirror.nju.edu.cn/pypi/web/simple, https://mirror.sjtu.edu.cn/pypi/web/simple, https://pypi.doubanio.com/simple

Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html

Ignoring tensorboard: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment

Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment

Ignoring tensorflow-metal: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment

ERROR: Could not find a version that satisfies the requirement accelerate~=0.18.0 (from versions: 0.0.1, 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1)

ERROR: No matching distribution found for accelerate~=0.18.0
