### ISSUE TITLE
Filename problems with NTFS on Windows

### ISSUE THREAD

**Issue by maximxlss** [d8ahazard/sd_dreambooth_extension#921]
On NTFS, some characters, like, for example `: ; < >`, are prohibited. These characters can be useful in prompts. You can use them, if you enter the prompt in a txt file, though this is not enough, as when generating classification images, they are named with a part of the prompt in the filename. This causes the plugin to fail saving the file.

**Comment by ArrowM** [comment]
I'm pretty sure this is fixed on main (https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/dreambooth/utils.py#L485). Please update your extension and respond back to this issue.

**Comment by maximxlss** [comment]
Sorry, I didn't have access to my PC for some time lately, so couldn't answer.

I'm on the last commit and the issue persists for me. Here is what it says:
```
Exception generating images: [WinError 87] Параметр задан неверно: 'C:\\stuff\\stable-diffusion\\clear\\stable-diffusion-webui\\models\\dreambooth\\kita\\classifiers_0\\kita ikuyo, 1girl, :D, solo, upper body, maid uniform, smile, wh-387fc5fb.tmp' -> 'C:\\stuff\\stable-diffusion\\clear\\stable-diffusion-webui\\models\\dreambooth\\kita\\classifiers_0\\kita ikuyo, 1girl, :D, solo, upper body, maid uniform, smile, wh-387fc5fb.tmp'
Traceback (most recent call last):
  File "C:\stuff\stable-diffusion\clear\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 980, in generate_classifiers
    image_filename = db_save_image(image, pd, custom_name=f"{pd.prompt[0:64]}-{image_base[0:8]}")
  File "C:\stuff\stable-diffusion\clear\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 512, in db_save_image
    os.replace(image_filename, image_filename)
OSError: [WinError 87] Параметр задан неверно: 'C:\\stuff\\stable-diffusion\\clear\\stable-diffusion-webui\\models\\dreambooth\\kita\\classifiers_0\\kita ikuyo, 1girl, :D, solo, upper body, maid uniform, smile, wh-387fc5fb.tmp' -> 'C:\\stuff\\stable-diffusion\\clear\\stable-diffusion-webui\\models\\dreambooth\\kita\\classifiers_0\\kita ikuyo, 1girl, :D, solo, upper body, maid uniform, smile, wh-387fc5fb.tmp'
```
`Параметр задан неверно` translates to `the parameter is incorrect`
If I move `:` to the end of the prompt, it works fine.


I also can't figure out what `os.replace(image_filename, image_filename)` does. It doesn't seem to do anything at all.
Without it, the same error occures in another place:
```
Exception generating images: [WinError 87] Параметр задан неверно: 'C:\\stuff\\stable-diffusion\\clear\\stable-diffusion-webui\\models\\dreambooth\\kita\\classifiers_0\\kita ikuyo, 1girl, :D, solo, upper body, maid uniform, smile, wh-bd7b5f83.tmp' -> 'C:\\stuff\\stable-diffusion\\clear\\stable-diffusion-webui\\models\\dreambooth\\kita\\classifiers_0\\kita ikuyo, 1girl, :D, solo, upper body, maid uniform, smile, wh-bd7b5f83.png'
Traceback (most recent call last):
  File "C:\stuff\stable-diffusion\clear\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 980, in generate_classifiers
    image_filename = db_save_image(image, pd, custom_name=f"{pd.prompt[0:64]}-{image_base[0:8]}")
  File "C:\stuff\stable-diffusion\clear\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 515, in db_save_image
    os.replace(image_filename, image_filename.replace(".tmp", ".png"))
OSError: [WinError 87] Параметр задан неверно: 'C:\\stuff\\stable-diffusion\\clear\\stable-diffusion-webui\\models\\dreambooth\\kita\\classifiers_0\\kita ikuyo, 1girl, :D, solo, upper body, maid uniform, smile, wh-bd7b5f83.tmp' -> 'C:\\stuff\\stable-diffusion\\clear\\stable-diffusion-webui\\models\\dreambooth\\kita\\classifiers_0\\kita ikuyo, 1girl, :D, solo, upper body, maid uniform, smile, wh-bd7b5f83.png'
```

That leaves the question how it creates a file in the first place without an error. And it actually tries to do that:
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        15.02.2023     15:42              0 kita ikuyo, 1girl,
```
The file is also undeletable with the Explorer or `Remove-Item` (Powershell). Only `del` manages to delete it.
